### ISSUE TITLE
Release file not found

### ISSUE THREAD

**Issue by Tony-Goat** [wanderers-guide/foundry-vtt-import#1]
Looks like you guys very recently changed the user account associated with the package and haven't made the release files for the module yet.

`Error: An unexpected error occurred when downloading file https://github.com/wanderers-guide/foundry-vtt-import/releases/download/0.1.0/module.zip: Not Found`

**Comment by Failtier** [comment]
I experience the same issue. Was thinking about permanently switching from Pathbuilder. But now this.

**Comment by Tony-Goat** [comment]
> I experience the same issue. Was thinking about permanently switching from Pathbuilder. But now this.

It's a relatively minor issue to fix, they just need to tag a commit and tell GitHub that it's a release tag. I would do it, but I'm not a maintainer on the project 🤷‍♂️

**Comment by Unknown-2-all** [comment]
I am interested in changing to Pathfinder 2e and looking at using this mod to help play the game. Hopefully, it can be fixed soon.

**Comment by Spectre-63** [comment]
same - even tried grabbing the raw file linked here and it also failed.  The instructions provided in the Readme similarly failed with the following error:
FoundryVTT | 2023-01-19 00:11:41 | [error] Invalid module "wanderers-guide-character-importer" detected in directory "pf2e-wanderers-guide-character-importer"

**Comment by ksignorini** [comment]
Well, crap. I was really hoping this would work.

**Comment by Spectre-63** [comment]
> Well, crap. I was really hoping this would work.

I expect it will, just a matter of waiting for the dev to fix whatever issues there are that are preventing the file from downloading/installing as expected.

**Comment by Tyrim** [comment]
Same issue here. Hopeful and waiting!

**Comment by Tony-Goat** [comment]
Quzzar has confirmed on the Discord server that they fixed the installation issue. The release file has been created and uploaded to the github repo.

I have personally confirmed that it works by installing it on my personal instance. You should delete the `Data/modules/pf2e-wanderers-guide-character-importer` folder as the module has been moved to the `Data/modules/wanderers-guide-character-importer` folder.

**Comment by ksignorini** [comment]
It now installs fine. However, it now gives an unmaintained/stability warning when launching the table.
